import React, {useState} from "react";

// The code exports a function called randomWord() which returns a random car brand name.
// The car brand names are stored in an array called carBrands.
// When randomWord() is called, it selects a random index in the carBrands array using Math.random() and Math.floor().
// The selected car brand is then converted to lowercase using .toLowerCase() and returned.

const carBrands = [
    "Acura",
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Bentley",
    "BMW",
    "Buick",
    "Cadillac",
    "Chevrolet",
    "Chrysler",
    "Citroën",
    "Dodge",
    "Ferrari",
    "Fiat",
    "Ford",
    "GMC",
    "Honda",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Jaguar",
    "Jeep",
    "Kia",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lincoln",
    "Lotus",
    "Maserati",
    "Mazda",
    "McLaren",
    "Mercedes-Benz",
    "Mini",
    "Mitsubishi",
    "Nissan",
    "Opel",
    "Peugeot",
    "Porsche",
    "RAM",
    "Renault",
    "Rolls-Royce",
    "Saab",
    "Saturn",
    "Scion",
    "Seat",
    "Škoda",
    "Smart",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "Ariel",
    "Ascari",
    "Bristol",
    "Bugatti",
    "Caterham",
    "Daimler",
    "De Tomaso",
    "Donkervoort",
    "Faraday Future",
    "Fisker",
    "Ginetta",
    "Gumpert",
    "Hennessey",
    "Koenigsegg",
    "Lada",
    "Lancia",
    "Lister",
    "Lucid Motors",
    "Mahindra",
    "Marcos",
    "Morgan",
    "Mosler",
    "Noble",
    "Pagani",
    "Polestar",
    "Proton",
    "Radical",
    "Rimac",
    "Roewe",
    "Singer",
    "Spyker",
    "Tata",
    "Tvr",
    "Ultima",
    "Venturi",
    "Wiesmann",
    "Zenvo"
];


function randomWord() {
    return carBrands[Math.floor(Math.random() * carBrands.length)].toLowerCase()
}

export {randomWord}